doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
        types:
            geometry:   LongitudeOne\Spatial\DBAL\Types\GeometryType
            point:      LongitudeOne\Spatial\DBAL\Types\Geometry\PointType
            polygon:    LongitudeOne\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: LongitudeOne\Spatial\DBAL\Types\Geometry\LineStringType
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                date_part:          BM2\SiteBundle\DQL\DatePart
            numeric_functions:
                #pow:                BM2\SiteBundle\DQL\Pow
                #round:              BM2\SiteBundle\DQL\Round
                st_point:           LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STPoint
                st_x:               LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STX
                st_y:               LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STY
                st_asgeojson:       LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsGeoJson
                st_astext:          LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
                st_contains:        LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                st_difference:      LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STDifference
                st_distance:        LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                st_closestpoint:    LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STClosestPoint
                st_dwithin:         LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STDWithin
                st_startpoint:      LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STStartPoint
                st_endpoint:        LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STEndPoint
                st_boundary:        LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STBoundary
                st_area:            LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                st_length:          LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                st_buffer:          LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STBuffer
                st_geomfromtext:    LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                st_line_interpolate_point:     LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineInterpolatePoint
                st_line_locate_point:          LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineLocatePoint
                st_line_substring:  LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineSubstring
                st_azimuth:         LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STAzimuth
                st_touches:         LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STTouches
                st_crosses:         LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STCrosses
                st_intersects:      LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersects
                st_intersection:    LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersection
                st_makebox2d:       LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeBox2D
                st_makeline:        LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine
                st_extent:          LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STExtent
                st_scale:           LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STScale
                st_union:           LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STUnion
                st_split:           LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STSplit
                st_geometryn:       LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeometryN

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
