doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                date_part:          BM2\SiteBundle\DQL\DatePart
            numeric_functions:
                #pow:                BM2\SiteBundle\DQL\Pow
                #round:              BM2\SiteBundle\DQL\Round
                st_point:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STPoint
                st_x:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STX
                st_y:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STY
                st_asgeojson:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsGeoJson
                st_astext:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
                st_contains:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                st_difference:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDifference
                st_distance:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                st_closestpoint:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STClosestPoint
                st_dwithin:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDWithin
                st_startpoint:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STStartPoint
                st_endpoint:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STEndPoint
                st_boundary:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STBoundary
                st_area:            CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                st_length:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                st_buffer:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STBuffer
                st_geomfromtext:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                st_line_interpolate_point:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineInterpolatePoint
                st_line_locate_point:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineLocatePoint
                st_line_substring:  CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineSubstring
                st_azimuth:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAzimuth
                st_touches:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STTouches
                st_crosses:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCrosses
                st_intersects:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersects
                st_intersection:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersection
                st_makebox2d:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeBox2D
                st_makeline:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine
                st_extent:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STExtent
                st_scale:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STScale
                st_union:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STUnion
                st_split:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSplit
                st_geometryn:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeometryN

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
