twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
            site_name: '%env(SITE_NAME)%'
            site_short: '%env(SITE_SHORT)%'
            activityDispathcer: '@App\Service\Dispatcher\ActivityDispatcher'
            associationDispatcher: '@App\Service\Dispatcher\AssociationDispatcher'
            appstate: '@App\Service\AppState'
            common: '@App\Service\CommonService'
            dispatcher: '@App\Service\Dispatcher\Dispatcher'
            unitDispatcher: '@App\Service\Dispatcher\UnitDispatcher'
            warDispatcher: '@App\Service\Dispatcher\WarDispatcher'

when@test:
    twig:
        strict_variables: true
