twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
            site_name: '%env(SITE_NAME)%'
            site_short: '%env(SITE_SHORT)%'
            activityDispathcer: '@App\Service\ActivityDispatcher'
            appstate: '@App\Service\AppState'
            common: '@App\Service\CommonService'
            dispatcher: '@App\Service\Dispatcher'
            unitDispatcher: '@App\Service\UnitDispatcher'

when@test:
    twig:
        strict_variables: true
